---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: k8s-config
  namespace: aakash
spec:
  interval: 5m
  path: ./aakash
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-config
  timeout: 2m