---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubewatch
  namespace: default
spec:
  chart:
    spec:
      chart: kubewatch
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 5m
  values:
    replicaCount: 2