apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmChart
metadata:
  name: cluster-autoscaler
  namespace: default
spec:
  chart: cluster-autoscaler
  version: 9.10.3
  sourceRef:
    name: auto-scaler
    kind: HelmRepository
  interval: 5m
